#!/usr/bin/env python3
# SPDX-FileCopyrightText: Samsung Electronics Co., Ltd
#
# SPDX-License-Identifier: BSD-3-Clause
"""
Emit a C translation unit holding a file's bytes

For binaries the build produces but the compiler cannot consume, such as a GPU
code object the library loads at runtime. The symbol names the array; its
length follows with a "_len" suffix.
"""
import sys
from pathlib import Path


def main(args):
    if len(args) != 3:
        print(f"usage: {sys.argv[0]} <input> <output.c> <symbol>", file=sys.stderr)
        return 1

    src, dst, symbol = Path(args[0]), Path(args[1]), args[2]
    data = src.read_bytes()

    lines = [
        "// Generated by toolbox/meson_embed.py; do not edit",
        "#include <stddef.h>",
        f"const unsigned char {symbol}[] = {{",
    ]
    for pos in range(0, len(data), 16):
        lines.append("\t" + ", ".join(f"0x{b:02x}" for b in data[pos : pos + 16]) + ",")
    lines += [
        "};",
        f"const size_t {symbol}_len = {len(data)};",
        "",
    ]
    dst.write_text("\n".join(lines))

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
