[xnvme.repository]
remote = "https://github.com/xnvme/xnvme.git"
path = "{{ local.env.HOME }}/git/xnvme"

[xnvme.repository.sync]
branch = "wip"
remote = "guest"
remote_path = "/root/git/xnvme"

[build.compiler]
bin = "gcc"

[[devices]]
uri = "2GB"
nsid = 1
labels = [ "dev", "bdev", "nvm", "ramdisk", "scc" ]
driver_attachment = "kernel"

[fio]
bin = "fio"

# Uncomment this to configure the build of fio with --prefix
#[fio.build]
#prefix = "/opt/fio"

[fio.repository]
remote = "https://github.com/axboe/fio.git"
path = "/root/git/fio"
tag = "fio-3.36"

[fio.engines.libaio]
type = "builtin"

[fio.engines.io_uring]
type = "builtin"

[fio.engines.io_uring_cmd]
type = "builtin"

[fio.engines.xnvme]
type = "builtin"

[fio.engines.spdk_nvme]
path = "/opt/aux/spdk_nvme"
type = "external_preload"

[fio.engines.spdk_bdev]
path = "/opt/aux/spdk_bdev"
type = "external_preload"
