# This is a generic collection of images for system imaging
[system-imaging.images.debian-13-x86_64]
system_label = "x86_64"

cloud.url = "https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-generic-amd64-daily.qcow2"
cloud.path = "{{ local.env.HOME }}/system_imaging/cloudinit/debian-13-generic-amd64-daily.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-metadata'] }}"
cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-userdata'] }}"

disk.url = "https://u489897-sub1:PublicAccess1!@u489897-sub1.your-storagebox.de/debian-trixie-amd64.qcow2"
disk.path = "{{ local.env.HOME }}/system_imaging/disk/debian-trixie-amd64.qcow2"

[system-imaging.images.debian-12-x86_64]
system_label = "x86_64"

cloud.url = "https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-amd64-daily.qcow2"
cloud.path = "{{ local.env.HOME }}/system_imaging/cloudinit/debian-12-generic-amd64-daily.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-metadata'] }}"
cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-userdata'] }}"

disk.url = "https://u489897-sub1:PublicAccess1!@u489897-sub1.your-storagebox.de/debian-12-x86_64.qcow2"
disk.path = "{{ local.env.HOME }}/system_imaging/disk/debian-12-x86_64.qcow2"

[system-imaging.images.debian-12-aarch64]
system_label = "aarch64"

cloud.url = "https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-arm64-daily.qcow2"
cloud.path = "{{ local.env.HOME }}//system_imaging/cloudinit/debian-12-generic-arm64-daily.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['cloudinit-debian-meta'] }}"
cloud.userdata_path = "{{ resources.auxiliary['cloudinit-debian-user-arm64'] }}"

disk.url = "https://u489897-sub1:PublicAccess1!@u489897-sub1.your-storagebox.de/debian-bookworm-arm64.qcow2"
disk.path = "{{ local.env.HOME }}/system_imaging/disk/debian-bookworm-arm64.qcow2"

[system-imaging.images.freebsd-13-x86_64]
system_label = "x86_64"

cloud.url = "https://refenv.fra1.digitaloceanspaces.com/freebsd13-ufs-ksrc.qcow2"
cloud.path = "{{ local.env.HOME}}/system_imaging/cloudinit/freebsd13-ufs-ksrc.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['cloudinit-freebsd-meta'] }}"
cloud.userdata_path = "{{ resources.auxiliary['cloudinit-freebsd-user'] }}"

disk.url = "https://u489897-sub1:PublicAccess1!@u489897-sub1.your-storagebox.de/freebsd-13.1-ksrc-amd64.qcow2"
disk.path = "{{ local.env.HOME }}/system_imaging/disk/freebsd-13-amd64.qcow2"

[system-imaging.images.freebsd-14-x86_64]
system_label = "x86_64"

cloud.url = "https://refenv.fra1.digitaloceanspaces.com/boot_images/freebsd-14.1-ksrc-amd64.qcow2"
cloud.path = "{{ local.env.HOME}}/system_imaging/cloudinit/freebsd-14.1-ksrc-amd64.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['cloudinit-freebsd-meta'] }}"
cloud.userdata_path = "{{ resources.auxiliary['cloudinit-freebsd-user'] }}"

disk.url = "https://u489897-sub1:PublicAccess1!@u489897-sub1.your-storagebox.de/freebsd-14.1-ksrc-amd64.qcow2"
disk.path = "{{ local.env.HOME }}/system_imaging/disk/freebsd-14.1-ksrc-amd64.qcow2"

[system-imaging.images.windows-11]
system_label = "x86_64"

disk.path = "{{ local.env.HOME }}/system_imaging/disk/win11.qcow2"