[xnvme.repository]
remote = "https://github.com/xnvme/xnvme.git"
path = "{{ local.env.HOME }}/git/xnvme"

# This is utilized by repository syncing during development.
[xnvme.repository.sync]
branch = "wip"
remote_alias = "guest"
remote_path = "/root/git/xnvme"

[xnvme.build]
type = "debug"
