#!/usr/bin/env bash
# Call the source-format script
exec 1>&2
if [[ -v GIT_HOOKS_OFF ]]; then
	echo "**Ignoring precommit / git-hooks**"
	exit 0
fi

cd scripts
if ! ./source-format.sh; then
	cat <<\EOF
==============================================================================
 Error: invalid source-format
==============================================================================

* You can inspect the current format-issues here: 'scripts/source-format.log'

* Run the source-formatter / fix the source-format issues

* Have a look at 'scripts/source-format.sh' for usage instructions

NOW: Fix the source-format and then commit again.

------------------------------------------------------------------------------

In case you are rebasing, and this is getting in your way, then disable the
pre-commit hook by setting the environment variable GIT_HOOKS_OFF for example
when using Bash:

  export GIT_HOOKS_OFF=1

==============================================================================
EOF
	exit 1
fi
exit 0
