///< This file is autogenerated by 'scripts/xnvme_3p.py'
const char *xnvme_3p_ver[] = {
	"fio;git-describe:fio-3.28",
#ifdef XNVME_BE_LINUX_LIBURING_ENABLED
	"liburing;git-describe:liburing-2.1",
#else
	"liburing;NOSYS",
#endif
#ifdef XNVME_BE_SPDK_ENABLED
	"spdk;git-describe:v21.10;+patches",
#else
	"spdk;NOSYS",
#endif
	0,	///< For array-termination
};
