# The SSH options are passed verbatim to paramiko; see
# https://www.paramiko.org/ This is common CIJOE infrastructure
#
# Used by: cijoe.run() / cijoe.get() / cijoe.put()
[cijoe.transport.qemu_guest]
username = "root"
password = "root"
hostname = "localhost"
port = 4200

[cijoe.workflow]
fail_fast=true

# Used by: the qemu.*.py scripts
[qemu]
img_bin = "qemu-img"

[qemu.systems.x86_64]
bin = "qemu-system-x86_64"

[qemu.guests.generic-bios-kvm-x86_64]
path = "{{ local.env.HOME }}/guests/generic-bios-kvm-x86_64"

system_label = "x86_64"
system_args.kwa = {cpu = "host", smp = 6, m = "32G", accel = "kvm"}
system_args.raw = """\
-M "type=q35,kernel_irqchip=split" \
-device pcie-root-port,id=rp_nvme,chassis=2,slot=2 \
-device vfio-pci,host=0000:02:00.0,bus=rp_nvme
"""
system_args.tcp_forward = {host = 4200, guest = 22}
