///< This file is autogenerated by 'scripts/xnvme_3p.py'
const char *xnvme_3p_ver[] = {
	"fio;git-describe:fio-3.27",
#ifdef XNVME_BE_LINUX_ENABLED
	"libnvme;git-rev:master/a458217",
#else
	"libnvme;NOSYS",
#endif
#ifdef XNVME_BE_LINUX_LIBURING_ENABLED
	"liburing;git-describe:liburing-2.0",
#else
	"liburing;NOSYS",
#endif
#ifdef XNVME_BE_SPDK_ENABLED
	"spdk;git-describe:v21.04;+patches",
#else
	"spdk;NOSYS",
#endif
	0,	///< For array-termination
};
