---
name: verify

on:
  push:
    branches: [main, next, docs]
    tags: ['v*']
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches: [next]
  workflow_dispatch:
    inputs:
      job:
        description: 'Job'
        required: true
        default: docgen
        type: choice
        options:
        - analyze
        - verify
        - bench
        - docgen

defaults:
  run:
    shell: bash

jobs:
  #
  # Produce a source-archive (with and without subprojects)
  #
  # with-subprojects
  # 
  #   To provide an artifact consisting of xNVMe and dependent projects for
  #   CI to consume as well as users in environments with no network access, a
  #   one-stop shop
  #
  # without-subprojects
  # 
  #   Primarily for system-package maintainers, for these then the dependencies
  #   are solved via the package-manager and related packages that may or
  #   may not be available, and thus, no "bundled" dependencies. Also, for
  #   minimalistic users, that does not need the external deps of e.g. SPDK
  #   and libvfn.
  #
  source-archive:
    runs-on: ubuntu-latest
    container: ghcr.io/xnvme/xnvme-deps-alpine-latest:next
    strategy:
      matrix:
        variant: [with-subprojects, without-subprojects]
    steps:
    - name: Grab source
      uses: actions/checkout@v4

    - name: Add repos to git-config safe.directory
      run: |
        git config --global --add safe.directory $(pwd)

    - name: Check repository...
      run: |
        ls -lha
        git status

    - name: Generate Source Archive
      run: |
        if [ "${{ matrix.variant }}" = "with-subprojects" ]; then
          make clean gen-src-archive-with-subprojects
        else
          make clean gen-src-archive
        fi

    - name: Rename to un-versioned xnvme-src.tar.gz
      run: |
        mv builddir/meson-dist/xnvme-0.7.5.tar.gz builddir/meson-dist/xnvme-src.tar.gz
        mv builddir/meson-dist/xnvme-0.7.5.tar.gz.sha256sum builddir/meson-dist/xnvme-src.tar.gz.sha256sum

    - name: Upload source archive
      uses: actions/upload-artifact@v4.3.0
      with:
        name: xnvme-src-archive${{ matrix.variant == 'with-subprojects' && '-with-subprojects' || '' }}
        path: |
          builddir/meson-dist/xnvme-src.tar.gz.sha256sum
          builddir/meson-dist/xnvme-src.tar.gz
        if-no-files-found: error

  #
  # Check source-format using pre-commit
  #
  source-format-check:
    runs-on: ubuntu-latest
    container: ghcr.io/xnvme/xnvme-deps-fedora-citools:next

    steps:
    - name: Grab source
      uses: actions/checkout@v4

    - name: Add repos to git-config safe.directory
      run: |
        git config --global --add safe.directory $(pwd)

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Run pre-commit
      run: pre-commit run --all-files

  #
  # Ensure that bash completions and man pages can be generated without error
  #
  test-gen-targets:
    needs: source-archive
    runs-on: ubuntu-latest
    container: ghcr.io/xnvme/xnvme-deps-citools-latest:next

    steps:
    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Build xNVMe
      run: make common

    - name: Install xNVMe
      run: make install

    - name: ldconfig
      run: ldconfig

    - name: Execute 'xnvme library-info'
      run: xnvme library-info

    - name: Run make gen-bash-completions
      run: make gen-bash-completions

    - name: Run make gen-man-pages
      run: make gen-man-pages

  build-rust:
    needs: source-archive
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xnvme/xnvme-deps-debian-bookworm:next

    steps:
    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Install dependencies
      run: |
        apt-get update -qy
        apt-get install -qy curl libclang-dev

    - name: Build xNVMe
      run: make common

    - name: Install xNVMe
      run: make install

    - name: ldconfig
      run: ldconfig

    - name: Execute 'xnvme library-info'
      run: xnvme library-info

    - uses: dtolnay/rust-toolchain@stable

    - name: Rust, generate and build bindings
      run: cargo build --release --manifest-path rust/Cargo.toml

    - name: Rust, run example
      run: cargo run --manifest-path rust/Cargo.toml

  #
  # Build xNVMe Python packages
  #
  build-python:
    needs: source-archive
    runs-on: ubuntu-latest
    container: ghcr.io/xnvme/xnvme-deps-debian-bullseye:next
    strategy:
      fail-fast: false

    steps:
    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Python sdist-packages, system-package deps.
      run: |
        apt-get install -qy libclang-13-dev

    - name: Python sdist-packages, build bindings
      run: |
        pushd python/bindings
        make clean build
        popd

    - name: Python sdist-packages, find(...)
      run: |
        find python/ -name *tar.gz

    - name: Rename
      run: |
        mv python/bindings/dist/xnvme-*.*.*.tar.gz python/bindings/dist/xnvme-py-sdist.tar.gz

    - name: Python sdist-packages, upload bindings
      uses: actions/upload-artifact@v4.3.0
      with:
        name: xnvme-py-sdist
        path: |
          python/bindings/dist/xnvme-py-sdist.tar.gz
        if-no-files-found: error

  #
  # Build on Linux using different Linux distributions
  #
  build-linux:
    needs: [source-archive, source-format-check, build-python]
    runs-on: ubuntu-latest
    if: contains('push pull_request', github.event_name)
    strategy:
      fail-fast: false
      matrix:
        container:
        # Using an alpine container which is the same as upstream but with bash
        # alpine: SPDK not supported, --with-spdk=disabled
        - {os: 'alpine', dh: 'refenv/alpine-bash', ver: 'latest'}
        - {os: 'archlinux', dh: 'archlinux', ver: 'latest'}
        - {os: 'centos', dh: 'tgagor/centos', ver: 'stream9'}
        - {os: 'debian', dh: 'debian', ver: 'bookworm'}
        - {os: 'debian', dh: 'debian', ver: 'bullseye'}
        - {os: 'debian', dh: 'debian', ver: 'trixie'}
        - {os: 'fedora', dh: 'fedora', ver: '39'}
        - {os: 'fedora', dh: 'fedora', ver: '40'}
        # Skipping fedora-41 due to broken libffi
        #- {os: 'fedora', dh: 'fedora', ver: '41'}
        - {os: 'gentoo', dh: 'gentoo/stage3', ver: 'latest'}
        - {os: 'opensuse-tumbleweed', dh: 'opensuse/tumbleweed', ver: 'latest'}
        - {os: 'oraclelinux', dh: 'oraclelinux', ver: '9'}
        - {os: 'rockylinux', dh: 'rockylinux', ver: '9.2'}
        - {os: 'ubuntu', dh: 'ubuntu', ver: 'focal'}
        - {os: 'ubuntu', dh: 'ubuntu', ver: 'jammy'}
        - {os: 'ubuntu', dh: 'ubuntu', ver: 'oracular'}

    container:
      image: ghcr.io/xnvme/xnvme-deps-${{ matrix.container.os }}-${{ matrix.container.ver }}:next

    steps:
    - name: Container-preparation, openSUSE does not have tar and gzip...
      if: contains(matrix.container.os, 'opensuse')
      run: zypper --non-interactive install -y tar gzip

    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Configure with and build with debug enabled (without spdk)
      if: ${{ contains(matrix.container.os, 'alpine') }}
      run: |
        meson setup builddir --buildtype=debug -Dwith-spdk=disabled
        meson compile -C builddir
        make clean # prepare for building without debug

    - name: Configure with debug enabled
      if: ${{ ! contains(matrix.container.os, 'alpine') }}
      run: |
        meson setup builddir --buildtype=debug
        meson compile -C builddir
        make clean # prepare for building without debug

    - name: Configure, Build, and Install
      env:
        BSCRIPT_DEF: toolbox/pkgs/default-build.sh
        BSCRIPT: toolbox/pkgs/${{ matrix.container.os }}-${{ matrix.container.ver }}-build.sh
      run: |
        if [[ -f "${BSCRIPT}" ]]; then source ${BSCRIPT}; else source ${BSCRIPT_DEF}; fi

    - name: Execute 'ldconfig'
      # ldconfig doesn't work on alpine
      # centos7 needs "ldconfig /usr/lib/local" for python3 to work
      if: ${{!contains(matrix.container.os, 'alpine') && !contains(matrix.container.ver, 'centos7') && !contains(matrix.container.ver,
        'stream8')}}
      run: ldconfig

    - name: meson-log-dump
      if: always()
      run: |
        cat builddir/meson-logs/meson-log.txt || true

    - name: isal-log-dump
      if: always()
      run: |
        cat subprojects/spdk/isa-l/spdk-isal.log || true

    - name: Execute 'xnvme enum'
      run: xnvme enum

    - name: Execute 'xnvme library-info'
      run: xnvme library-info

    - name: Check pkg-config
      run: |
        pkg-config xnvme --libs
        pkg-config xnvme --variable=datadir
        pkg-config xnvme --variable=includedir
        pkg-config xnvme --variable=libdir
        pkg-config xnvme --variable=pcfiledir
        pkg-config xnvme --variable=prefix
        ls -lh $(pkg-config xnvme --variable=libdir) | grep xnvme

    - name: Check Python, pip, pipx, platform, sysconfig and setup PATH for pipx
      run: |
        python3 --version
        python3 -m pip --version
        python3 -c 'import setuptools; print("setuptools version:", setuptools.__version__)'
        python3 -c "import platform; print(platform.system()); print(platform.uname())"
        python3 -c 'import sysconfig; print(sysconfig.get_config_var("SHLIB_SUFFIX"))'
        python3 -m pipx --version
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Retrieve the xNVMe Python sdist package
      uses: actions/download-artifact@v4.1.7
      with:
        name: xnvme-py-sdist
        path: ${{ steps.source.outputs.directory }}

    # Setup Python virtual-environment for cijoe and Python xNVMe bindings to run ramdisk testing
    - name: CIJOE, setup pipx environment
      if: (!contains('focal', matrix.container.ver))
      run: |
        make cijoe

    - name: CIJOE, check that it is available
      if: (!contains('focal', matrix.container.ver))
      run: |
        cijoe -r

    - name: Python-bindings (ctypes), install and test
      if: (!contains('focal', matrix.container.ver))
      run: |
        python3 -m pipx inject cijoe "${{ steps.source.outputs.directory }}/xnvme-py-sdist.tar.gz"
        pytest --pyargs xnvme.ctypes_bindings

    #
    # Ramdisk testing
    #
    # Skipping on distros with too old gcc/clang to build fio, and too old a Python to run cijoe (requires 3.9)
    #
    - name: CIJOE, install fio
      if: (!contains('focal', matrix.container.ver))
      run: |
        cd cijoe && cijoe fio_prep \
        --monitor \
        --config "configs/ramdisk.toml" \
        --output "build-${{ matrix.container.os }}-${{ matrix.container.ver }}-prep-fio"

    - name: CIJOE, run test-ramdisk.yaml
      if: (!contains('focal', matrix.container.ver))
      run: |
        cd cijoe && cijoe "workflows/test-ramdisk.yaml" \
        --monitor \
        --config "configs/ramdisk.toml" \
        --output "build-${{ matrix.container.os }}-${{ matrix.container.ver }}-test-ramdisk"

    - name: CIJOE, archive build-${{ matrix.container.os }}-${{ matrix.container.ver }}-reports
      if: always() && (!contains('focal', matrix.container.ver))
      run: |
        tar czf build-${{ matrix.container.os }}-${{ matrix.container.ver }}-reports.tar.gz \
          cijoe/build-${{ matrix.container.os }}-${{ matrix.container.ver }}-* 

    - name: CIJOE, upload build-${{ matrix.container.os }}-${{ matrix.container.ver }}-reports
      if: always() && (!contains('focal', matrix.container.ver))
      uses: actions/upload-artifact@v4.3.0
      with:
        name: build-${{ matrix.container.os }}-${{ matrix.container.ver }}-reports
        path: build-${{ matrix.container.os }}-${{ matrix.container.ver }}-reports.tar.gz
        if-no-files-found: error

  #
  # Build on macOS
  #
  build-macos:
    needs: [source-archive, source-format-check, build-python]
    runs-on: ${{ matrix.runner.os }}-${{ matrix.runner.ver }}
    if: contains('push pull_request', github.event_name)

    strategy:
      fail-fast: false
      matrix:
        runner:
        - {os: 'macos', ver: '13'}
        - {os: 'macos', ver: '14'}
        - {os: 'macos', ver: '15'}

    steps:
    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Install build-requirements
      run: |
        source toolbox/pkgs/${{ matrix.runner.os }}-${{ matrix.runner.ver }}.sh || true

    - name: Prep, environment GITHUB_PATH
      run: |
        echo "/opt/homebrew/opt/make/libexec/gnubin" >> $GITHUB_PATH

    - name: Configure and build with debug enabled
      run: |
        meson setup builddir --buildtype=debug
        meson compile -C builddir
        make clean # prepare for building without debug

    - name: Configure, Build, and Install
      env:
        BSCRIPT_DEF: toolbox/pkgs/default-build.sh
        BSCRIPT: toolbox/pkgs/${{ matrix.runner.os }}-${{ matrix.runner.ver }}-build.sh
      run: |
        if [[ -f "${BSCRIPT}" ]]; then source ${BSCRIPT}; else source ${BSCRIPT_DEF}; fi

    - name: meson-log-dump
      if: always()
      run: |
        cat builddir/meson-logs/meson-log.txt || true

    - name: Execute 'xnvme enum'
      run: xnvme enum

    - name: Execute 'xnvme library-info'
      run: xnvme library-info

    - name: Check pkg-config
      run: |
        pkg-config xnvme --libs
        pkg-config xnvme --variable=datadir
        pkg-config xnvme --variable=includedir
        pkg-config xnvme --variable=libdir
        pkg-config xnvme --variable=pcfiledir
        pkg-config xnvme --variable=prefix
        ls -lh $(pkg-config xnvme --variable=libdir) | grep xnvme

    - name: Check Python, pip, platform, and sysconfig
      run: |
        python3 --version
        python3 -m pip --version
        python3 -c "import platform; print(platform.system()); print(platform.uname())"
        python3 -c 'import sysconfig; print(sysconfig.get_config_var("SHLIB_SUFFIX"))'

    - name: Retrieve the xNVMe Python sdist package
      uses: actions/download-artifact@v4.1.7
      with:
        name: xnvme-py-sdist
        path: ${{ steps.source.outputs.directory }}

    # Setup Python virtual-environment for cijoe and Python xNVMe bindings to run ramdisk testing
    - name: CIJOE, setup pipx environment
      run: |
        make cijoe

    - name: CIJOE, check that it is available
      run: |
        cijoe -r

    - name: Python-bindings (ctypes), install and test
      run: |
        pipx inject cijoe "${{ steps.source.outputs.directory }}/xnvme-py-sdist.tar.gz"
        pytest --pyargs xnvme.ctypes_bindings

    #
    # Ramdisk testing
    #
    - name: Install fio
      run: |
        git clone https://github.com/axboe/fio.git /tmp/fio
        cd /tmp/fio
        git checkout fio-3.38
        git rev-parse --short HEAD
        gmake

    - name: CIJOE, run test-ramdisk.yaml
      run: |
        cd cijoe && cijoe "workflows/test-ramdisk-macos.yaml" \
        --monitor \
        --config "configs/ramdisk-macos.toml" \
        --output "build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-test-ramdisk"

    - name: CIJOE, archive build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-reports
      if: always()
      run: |
        tar czf build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-reports.tar.gz \
          cijoe/build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-* 

    - name: CIJOE, upload build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-reports
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-reports
        path: build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-reports.tar.gz
        if-no-files-found: error

  #
  # Build on Windows
  #
  build-windows:
    needs: [source-archive, source-format-check, build-python]
    runs-on: ${{ matrix.runner.os }}-${{ matrix.runner.ver }}
    if: contains('push pull_request', github.event_name)
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        runner:
        - {os: 'windows', ver: '2025'}

    steps:
    - name: Setup paths
      shell: cmd
      run: |
        echo %ALLUSERSPROFILE%\chocolatey\bin>> %GITHUB_PATH%
        echo %SystemDrive%\tools\msys64\mingw64\bin>> %GITHUB_PATH%
        echo %SystemDrive%\tools\msys64>> %GITHUB_PATH%
        echo %SystemDrive%\tools\msys64\usr\lib>> %GITHUB_PATH%
        echo %SystemDrive%\tools\msys64\usr\bin>> %GITHUB_PATH%
        echo PKG_CONFIG_PATH=%SystemDrive%/tools/msys64/usr/lib/pkgconfig;%SystemDrive%\tools\msys64\usr\lib\pkgconfig >> %GITHUB_ENV%

    - name: Show paths
      shell: powershell
      run: |
        echo $env:Path

    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Install build-requirements
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        .\toolbox\pkgs\windows-2022.ps1

    - name: Configure and build with debug enabled
      shell: bash
      run: |
        meson setup builddir --buildtype=debug
        meson compile -C builddir
        make clean # prepare for building without debug

    - name: Build!
      shell: powershell
      run: |
        meson setup builddir --prefix "$env:SystemDrive\tools\msys64\usr" --default-library=static
        meson compile -C builddir

    - name: meson-log-dump
      shell: bash
      if: always()
      run: |
        cat builddir/meson-logs/meson-log.txt || true

    - name: Dump the compile-commands and machine
      shell: bash
      run: |
        cat /proc/cpuinfo || true
        cat builddir/compile_commands.json || true

    - name: Install
      run: |
        meson install -C builddir

    - name: Execute xnvme commands
      shell: powershell
      run: |
        xnvme.exe library-info
        xnvme.exe enum

    - name: Check pkg-config
      shell: bash
      run: |
        pkg-config xnvme --libs
        pkg-config xnvme --variable=datadir
        pkg-config xnvme --variable=includedir
        pkg-config xnvme --variable=libdir
        pkg-config xnvme --variable=pcfiledir
        pkg-config xnvme --variable=prefix
        ls -lh $(pkg-config xnvme --variable=libdir) | grep xnvme

    - name: Check Python, pip, platform, and sysconfig
      shell: bash
      run: |
        python3 --version
        python3 -m pip --version
        python3 -c "import platform; print(platform.system()); print(platform.uname())"
        python3 -c 'import sysconfig; print(sysconfig.get_config_var("SHLIB_SUFFIX"))'

    - name: Retrieve the xNVMe Python sdist package
      uses: actions/download-artifact@v4.1.7
      with:
        name: xnvme-py-sdist
        path: ${{ steps.source.outputs.directory }}

    # Setup Python virtual-environment for cijoe and Python xNVMe bindings to run ramdisk testing
    - name: CIJOE, setup pipx environment
      run: |
        make cijoe

    - name: CIJOE, check that it is available
      run: |
        cijoe -r

    #
    # Ramdisk testing
    #
    - name: Install fio
      shell: bash
      run: |
        rm -rf C:/tmp/fio
        git clone https://github.com/axboe/fio.git C:/tmp/fio
        cd C:/tmp/fio
        # git checkout fio-3.38
        git checkout 7037b833e175aae32900b73bf597aad08c1d8472 # windows: drop nanosleep and clock_gettime
        git rev-parse --short HEAD
        make clean
        make CFLAGS="-O0"

    - name: CIJOE, run test-ramdisk-windows.yaml
      shell: bash
      run: |
        cd cijoe; cijoe "workflows/test-ramdisk-windows.yaml" \
        --monitor \
        --config "configs/ramdisk-windows.toml" \
        --output "build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-test-ramdisk"

    - name: CIJOE, archive build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-reports
      if: always()
      run: |
        tar czf build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-reports.tar.gz \
          cijoe/build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-* 

    - name: CIJOE, upload build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-reports
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-reports
        path: build-${{ matrix.runner.os }}-${{ matrix.runner.ver }}-reports.tar.gz
        if-no-files-found: error

  #
  # Build and test xNVMe
  #
  verify:
    needs: [source-archive, source-format-check, build-python]
    runs-on: ubuntu-latest

    if: (contains('push pull_request', github.event_name) || ((github.event_name == 'workflow_dispatch') && (github.event.inputs.job
      == 'verify')))

    strategy:
      fail-fast: false
      matrix:
        guest:
        - {os: 'freebsd', ver: '13'}
        - {os: 'freebsd', ver: '14'}
        - {os: 'debian', ver: 'bullseye'}

    container:
      image: ghcr.io/xnvme/xnvme-qemu:latest
      options: --privileged

    steps:
    - uses: xnvme/actions/.github/actions/cleanup@main

    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Retrieve the xNVMe Python sdist package
      uses: actions/download-artifact@v4.1.7
      with:
        name: xnvme-py-sdist
        path: ${{ steps.source.outputs.directory }}

    - name: Prep, environment GITHUB_PATH
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        cp -r ${{ steps.source.outputs.directory }} /tmp/artifacts
        find /tmp/artifacts

    - name: Install python-venv on Bullseye
      run: |
        apt-get install -qy python3-venv

    - name: pipx, Install
      run: |
        python3 -m pip uninstall pytest cijoe -y
        python3 -m pip list
        python3 -m pip install pipx
        python3 -m pipx ensurepath

    - name: CIJOE, setup pipx environment
      run: |
        make cijoe

    - name: CIJOE, check that it is available
      run: |
        cijoe -r

    # cd'ing into 'cijoe' to auto-collect the non-packaged github-specific configs and
    # workflows.
    - name: CIJOE, run provision-using-tgz.yaml
      run: |
        cd cijoe && cijoe "workflows/provision-using-tgz.yaml" \
        --monitor \
        --config "configs/${{ matrix.guest.os }}-${{ matrix.guest.ver }}.toml" \
        --output "verify-${{ matrix.guest.os }}-${{ matrix.guest.ver }}-provision"

    - name: CIJOE, run test.yaml
      run: |
        cd cijoe && cijoe "workflows/test-${{ matrix.guest.os }}-${{ matrix.guest.ver }}.yaml" \
        --monitor \
        --config "configs/${{ matrix.guest.os }}-${{ matrix.guest.ver }}.toml" \
        --output "verify-${{ matrix.guest.os }}-${{ matrix.guest.ver }}-test-results"

    - name: CIJOE, result-log-dump on error
      if: failure()
      run: find cijoe -name "*.output" | xargs cat

    - name: CIJOE, archive verify-${{ matrix.guest.os }}-${{ matrix.guest.ver }}-reports
      if: always()
      run: |
        tar czf verify-${{ matrix.guest.os }}-${{ matrix.guest.ver }}-reports.tar.gz \
          cijoe/verify-${{ matrix.guest.os }}-${{ matrix.guest.ver }}-* 

    - name: CIJOE, upload verify-${{ matrix.guest.os }}-${{ matrix.guest.ver }}-reports
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: verify-${{ matrix.guest.os }}-${{ matrix.guest.ver }}-reports
        path: verify-${{ matrix.guest.os }}-${{ matrix.guest.ver }}-reports.tar.gz
        if-no-files-found: error

  #
  # Build and test xNVMe on physical machines
  #
  verify-physical:
    needs: [source-archive, source-format-check, build-python]
    runs-on: ${{ matrix.guest.labels }}

    if: (contains('push pull_request', github.event_name) || ((github.event_name == 'workflow_dispatch') && (github.event.inputs.job
      == 'verify')))

    strategy:
      fail-fast: false
      matrix:
        guest:
        - {os: 'macos', ver: 'sonoma', hostname: 'verify-phys-macos', labels: [self-hosted, macos, arm64, verify]}

    container:
      image: debian:bookworm
      options: --privileged

    steps:
    - uses: xnvme/actions/.github/actions/cleanup@main

    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Retrieve the xNVMe Python sdist package
      uses: actions/download-artifact@v4.1.7
      with:
        name: xnvme-py-sdist
        path: ${{ steps.source.outputs.directory }}

    - name: Prep, environment GITHUB_PATH
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        cp -r ${{ steps.source.outputs.directory }} /tmp/artifacts
        find /tmp/artifacts

    - name: Packages
      run: |
        apt-get -qy update
        apt-get -qy upgrade
        apt-get -qy install python3 python3-dev python3-venv pipx git make gcc fontconfig sshpass
        pipx ensurepath

    - name: CIJOE, setup pipx environment
      run: |
        make cijoe
        cijoe --version

    # cd'ing into 'cijoe' to auto-collect the non-packaged github-specific configs and
    # workflows.
    - name: CIJOE, run macvfn-provision.yaml
      if: matrix.guest.os == 'macos'
      run: |
        cd cijoe && cijoe "workflows/macvfn-provision.yaml" \
        --monitor \
        --config "configs/${{ matrix.guest.hostname }}.toml" \
        --output "verify-${{ matrix.guest.hostname }}-provision-macvfn"

    - name: CIJOE, run provisioning
      run: |
        cd cijoe && cijoe "workflows/provision-using-tgz.yaml" \
        --monitor \
        --config "configs/${{ matrix.guest.hostname }}.toml" \
        --output "verify-${{ matrix.guest.hostname }}-provision-xnvme" \
        xnvme_source_sync xnvme_build_prep xnvme_build xnvme_install \
        ldconfig xnvme_bindings_py_install_tgz fio_prep

    - name: CIJOE, run tests
      run: |
        cd cijoe && cijoe "workflows/test-${{ matrix.guest.os }}-${{ matrix.guest.ver }}.yaml" \
        --monitor \
        --config "configs/${{ matrix.guest.hostname }}.toml" \
        --output "verify-${{ matrix.guest.hostname }}-test-results"

    - name: CIJOE, result-log-dump on error
      if: failure()
      run: find cijoe -name "*.output" | xargs cat

    - name: CIJOE, archive verify-${{ matrix.guest.hostname }}-reports
      if: always()
      run: |
        tar czf verify-${{ matrix.guest.hostname }}-reports.tar.gz \
          cijoe/verify-${{ matrix.guest.hostname }}-* 

    - name: CIJOE, upload verify-${{ matrix.guest.hostname }}-reports
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: verify-${{ matrix.guest.hostname }}-reports
        path: verify-${{ matrix.guest.hostname }}-reports.tar.gz
        if-no-files-found: error

  #
  # Build and test xNVMe on physical hardware on MaaS
  #
  verify-maas:
    needs: [source-archive, source-format-check, build-python]
    runs-on: ${{ matrix.guest.labels }}

    if: (contains('push pull_request', github.event_name) || ((github.event_name == 'workflow_dispatch') && (github.event.inputs.job
      == 'verify')))

    strategy:
      fail-fast: false
      matrix:
        guest:
        - {os: 'debian', ver: 'bookworm', hostname: 'ax42-linux', labels: [self-hosted, linux, amd64, maas]}

    steps:
    - uses: xnvme/actions/.github/actions/cleanup@main

    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Retrieve the xNVMe Python sdist package
      uses: actions/download-artifact@v4.1.7
      with:
        name: xnvme-py-sdist
        path: ${{ steps.source.outputs.directory }}

    - name: Prep, environment GITHUB_PATH
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        cp -r ${{ steps.source.outputs.directory }} /tmp/artifacts
        find /tmp/artifacts

    - name: CIJOE, setup pipx environment
      run: |
        make cijoe
        cijoe --version

    - name: CIJOE, run provisioning
      run: |
        cd cijoe && cijoe \
        "workflows/provision-maas-using-tgz.yaml" \
        --monitor \
        --config "configs/${{ matrix.guest.hostname }}.toml" \
        --config "configs/${{ matrix.guest.hostname }}-testing.toml" \
        --output "verify-${{ matrix.guest.hostname }}-provision"

    - name: CIJOE, run tests
      run: |
        cd cijoe && cijoe \
        workflows/test-${{ matrix.guest.os }}-${{ matrix.guest.ver }}.yaml \
        --monitor \
        --config "configs/${{ matrix.guest.hostname }}.toml" \
        --config "configs/${{ matrix.guest.hostname }}-testing.toml" \
        --output "verify-${{ matrix.guest.hostname }}-test-results"

    - name: CIJOE, result-log-dump on error
      if: failure()
      run: find cijoe -name "*.output" | xargs cat

    - name: CIJOE, archive verify-${{ matrix.guest.hostname }}-reports
      if: always()
      run: |
        tar czf verify-${{ matrix.guest.hostname }}-reports.tar.gz \
          cijoe/verify-${{ matrix.guest.hostname }}-* 

    - name: CIJOE, upload verify-${{ matrix.guest.hostname }}-reports
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: verify-${{ matrix.guest.hostname }}-reports
        path: verify-${{ matrix.guest.hostname }}-reports.tar.gz
        if-no-files-found: error


  #
  # Build and run performance test of xNVMe
  #
  benchmark-bdev_xnvme:
    needs: [source-archive, source-format-check, build-python]
    runs-on: [self-hosted, linux, X64, bench, intel]

    if: (contains('push', github.event_name) || ((github.event_name == 'workflow_dispatch') && (github.event.inputs.job ==
      'bench')) || ((github.event_name == 'pull_request') && contains(github.event.pull_request.labels.*.name, 'bench')))

    strategy:
      fail-fast: false

    container:
      image: debian:bookworm
      options: --privileged

    steps:
    - uses: xnvme/actions/.github/actions/cleanup@main

    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Prep, environment GITHUB_PATH
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        cp -r ${{ steps.source.outputs.directory }} /tmp/artifacts
        find /tmp/artifacts -name "*.tar.gz"

    - name: Packages, Debian Bookworm
      run: |
        apt-get -qy update
        apt-get -qy upgrade
        apt-get -qy install python3 python3-dev python3-venv pipx git make gcc fontconfig
        pipx ensurepath

    - name: CIJOE, setup pipx environment
      run: |
        make cijoe

    - name: CIJOE, provision xnvme from tgz
      run: |
        rm -rf cijoe/scalability-provision-xnvme
        cd cijoe && cijoe "workflows/provision-using-tgz.yaml" \
        --monitor \
        --config "configs/bench-intel.toml" \
        --output "scalability-provision-xnvme" \
        xnvme_source_sync xnvme_build_prep xnvme_build \
        xnvme_install ldconfig fio_prep

    - name: CIJOE, run benchmark provisioning
      run: |
        cd cijoe && cijoe "workflows/benchmark-provisioning-linux.yaml" \
        --monitor \
        --config "configs/bench-intel.toml" \
        --output "scalability-provision-bench"

    - name: CIJOE, run bench
      run: |
        rm -rf cijoe/bench-results
        cd cijoe && cijoe "workflows/bench.yaml" \
        --monitor \
        --config "configs/bench-intel.toml" \
        --output "scalability-benchmark-results"

    - name: CIJOE, archive scalability-reports
      if: always()
      run: |
        tar czf scalability-reports.tar.gz \
          cijoe/scalability-* 

    - name: CIJOE, upload scalability-reports
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: scalability-reports
        path: scalability-reports.tar.gz
        if-no-files-found: error

  #
  # Build and run fio latency test of xNVMe
  #
  benchmark-latency:
    needs: [source-archive, source-format-check, build-python]
    if: (contains('push', github.event_name) || ((github.event_name == 'workflow_dispatch') && (github.event.inputs.job ==
      'bench')) || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'bench')))

    strategy:
      fail-fast: false
      matrix:
        guest:
        - {os: 'linux', labels: [self-hosted, linux, amd64, maas]}
        - {os: 'freebsd', labels: [self-hosted, linux, amd64, maas]}
        - {os: 'windows', labels: [self-hosted, linux, amd64, maas]}

    runs-on: ${{ matrix.guest.labels }}

    steps:
    - uses: xnvme/actions/.github/actions/cleanup@main

    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Retrieve the xNVMe Python sdist package
      uses: actions/download-artifact@v4.1.7
      with:
        name: xnvme-py-sdist
        path: ${{ steps.source.outputs.directory }}

    - name: Prep, environment GITHUB_PATH
      run: |
        cp -r ${{ steps.source.outputs.directory }} /tmp/artifacts
        find /tmp/artifacts
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: CIJOE, setup pipx environment
      run: |
        make cijoe
        cijoe --version

    - name: CIJOE, provision xnvme from tgz
      run: |
        cd cijoe && cijoe \
        "workflows/provision-maas-using-tgz.yaml" \
        --monitor \
        --config "configs/ax42-${{ matrix.guest.os }}.toml" \
        ${{ matrix.guest.os == 'windows' && 'guest_kill guest_initialize windows_qemu_prep windows_guest_start guest_check packages_extra xnvme_source_sync xnvme_build_prep xnvme_build xnvme_install fio_prep' || '' }} \
        --output "latency-${{ matrix.guest.os }}-provision-xnvme"

    - name: CIJOE, run latency benchmark
      run: |
        rm -rf cijoe/latency-${{ matrix.guest.os }}-benchmark
        cd cijoe && cijoe "workflows/benchmark-latency.yaml" \
        --monitor \
        --config "configs/ax42-${{ matrix.guest.os }}.toml" \
        --output "latency-${{ matrix.guest.os }}-benchmark"

    - name: CIJOE, archive latency-${{ matrix.guest.os }}-reports
      if: always()
      run: |
        tar czf latency-${{ matrix.guest.os }}-reports.tar.gz \
          cijoe/latency-${{ matrix.guest.os }}-*

    - name: CIJOE, upload latency-${{ matrix.guest.os }}-reports
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: latency-${{ matrix.guest.os }}-reports
        path: latency-${{ matrix.guest.os }}-reports.tar.gz
        if-no-files-found: error

  #
  # Documentation: generate documentation and deploy it to githubpages (xnvme.io)
  #
  # This is triggered upon:
  #
  # * push of branches and tags
  # * manual 'workflow_dispatch'
  # * pull-request changes, thus, we can catch whether a PR breaks documentation
  #
  # When triggered by 'push' or 'workflow_dispatch', then the documentation is
  # deployed to:
  #
  #   githubpages/docs/<github.ref>
  #
  # A couple of examples:
  #
  # * githubpages/docs/next
  # * githubpages/docs/current
  # * githubpages/docs/foo
  # * githubpages/docs/v1.2.3
  # * githubpages/docs/v1.2.4
  #
  # Thus, upon push/dispatch then the archive/history is updated
  # The root of the site is always synced with githubpages/docs/current in case
  # there are no changes to "docs/current", then there is nothing to commit
  #
  docgen:
    needs: [source-archive, source-format-check, build-python]
    runs-on: ubuntu-latest
    if: ((github.event_name == 'push') || (github.event_name == 'pull_request') || ((github.event_name == 'workflow_dispatch')
      && (github.event.inputs.job == 'docgen')))

    strategy:
      fail-fast: false
      matrix:
        guest:
        - {os: 'debian', ver: 'bullseye'}

    container:
      image: ghcr.io/xnvme/xnvme-qemu:latest
      options: --privileged

    steps:
    - uses: xnvme/actions/.github/actions/cleanup@main

    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Container-prep
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Retrieve the xNVMe Python sdist package
      uses: actions/download-artifact@v4.1.7
      with:
        name: xnvme-py-sdist
        path: ${{ steps.source.outputs.directory }}

    - name: Move source-archives to /tmp/artifacts
      run: |
        ls -lh
        find . -name "*.tar.gz"
        find /tmp -name "*.tar.gz"
        rm -r /tmp/artifacts || true
        cp -r ${{ steps.source.outputs.directory }} /tmp/artifacts
        find /tmp/artifacts -name "*.tar.gz"

    - name: Install python-venv on Bullseye
      run: |
        apt-get install -qy python3-venv

    - name: pipx, Install
      run: |
        python3 -m pip uninstall pytest cijoe -y
        python3 -m pip list
        python3 -m pip install pipx
        python3 -m pipx ensurepath

    - name: CIJOE, setup pipx environment
      run: |
        make cijoe

    - name: CIJOE, check that it is available
      run: |
        cijoe -r

    # cd'ing into 'cijoe' to auto-collect the non-packaged github-specific configs and
    # workflows.
    - name: CIJOE, run provision-using-tgz.yaml
      run: |
        cd cijoe && cijoe "workflows/provision-using-tgz.yaml" \
        --monitor \
        --config "configs/${{ matrix.guest.os }}-${{ matrix.guest.ver }}.toml" \
        --output "provision-${{ matrix.guest.os }}-${{ matrix.guest.ver }}"

    - name: CIJOE, generate documentation
      run: |
        cd cijoe && cijoe "workflows/docgen.yaml" \
        --monitor \
        --config "configs/${{ matrix.guest.os }}-${{ matrix.guest.ver }}.toml" \
        --output "docgen-${{ matrix.guest.os }}-${{ matrix.guest.ver }}"

    - name: Checkout site
      if: ((github.event_name == 'push') || ((github.event_name == 'workflow_dispatch') && (github.event.inputs.job == 'docgen')))
      uses: actions/checkout@v4
      with:
        repository: "xnvme/xnvme.github.io"
        token: ${{ secrets.DOCS_PAT }}
        path: site

    - name: Add repos to git-config safe.directory
      run: |
        git config --global --add safe.directory $(pwd)/site

    - name: Extract the website
      if: ((github.event_name == 'push') || ((github.event_name == 'workflow_dispatch') && (github.event.inputs.job == 'docgen')))
      run: |
        cp cijoe/docgen-${{ matrix.guest.os }}-${{ matrix.guest.ver }}/artifacts/docs.tar.gz .
        tar xzf docs.tar.gz

    - name: Update site repository
      if: ((github.event_name == 'push') || ((github.event_name == 'workflow_dispatch') && (github.event.inputs.job == 'docgen')))
      run: |
        ./docs/autogen/dest.py --docs html --site site --ref "${{ github.ref }}"

    - name: Push site-changes
      if: ((github.event_name == 'push') || ((github.event_name == 'workflow_dispatch') && (github.event.inputs.job == 'docgen')))
      run: |
        cd site
        git config --global user.name 'GitHUB Service'
        git config --global user.email 'ghs@safl.dk'
        git add .
        git commit -a -m "Auto-deployed update of 'docs/' for '${{ github.ref }}'"
        git push

    - name: CIJOE, upload report-docgen
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: docgen-results-${{ matrix.guest.os }}-${{ matrix.guest.ver }}
        path: cijoe/docgen-${{ matrix.guest.os }}-${{ matrix.guest.ver }}/*
        if-no-files-found: error

  #
  # All of the following "analysis" jobs only trigger on 'workflow_dispatch'
  #

  #
  # Code-analysis using scan-build
  #
  analyze-scan-build:
    needs: source-archive
    runs-on: ubuntu-latest
    container: ghcr.io/xnvme/xnvme-deps-citools-latest:next
    if: ((github.event_name == 'workflow_dispatch') && (github.event.inputs.job == 'analyze'))

    steps:
    - name: Retrieve, unpack, and remove the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Run config-debug
      run: scan-build make config-debug

    - name: Run scan-build
      run: scan-build --exclude subprojects -o /tmp/scan-build-report make

    - name: Upload scan-build report
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: scan-build-report
        path: /tmp/scan-build-report/*
        if-no-files-found: error

  #
  # Code-analysis using GitHUB CodeQL
  #
  analyze-codeql:
    needs: source-archive
    runs-on: ubuntu-latest
    container: debian:bullseye
    if: ((github.event_name == 'workflow_dispatch') && (github.event.inputs.job == 'analyze'))

    steps:
    - name: Retrieve, unpack, and remove the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: Install build-requirements
      run: source toolbox/pkgs/debian-bullseye.sh

    - name: Configure, the build
      run: make config

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'cpp'
        config-file: ./.github/codeql/codeql-config.yml

    - name: Build
      run: make -j $(nproc)

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  #
  # Code-analysis using Coverity
  #
  analyze-coverity:
    needs: source-archive
    runs-on: ubuntu-latest
    if: ((github.event_name == 'workflow_dispatch') && (github.event.inputs.job == 'analyze'))

    container: debian:buster
    env:
      COVERITY_TGZ_PATH: "/tmp/cov-analysis-linux64.tar.gz"
      COVERITY_ROOT: "/tmp/cov-analysis-linux64"
      PROJECT_NAME: "xNVMe"

    steps:
    - name: Retrieve, unpack, and remove the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive-with-subprojects

    - name: xNVMe, install build-requirements
      run: |
        source toolbox/pkgs/debian-buster.sh

    - name: xNVMe, configure the build
      run: |
        make config

    - name: xNVMe, dump the compile-commands and machine
      run: |
        cat /proc/cpuinfo || true
        cat build/compile_commands.json || true

    - name: Project, define version env. var.
      run: |
        PROJECT_VERSION=$(python3 toolbox/xnvme_ver.py --path meson.build)
        echo "PROJECT_VERSION=${PROJECT_VERSION}" >> $GITHUB_ENV

    - name: Coverity, install requirements
      run: |
        apt-get install -qy wget curl

    - name: Coverity, download
      run: |
        wget -q https://scan.coverity.com/download/cxx/linux64 \
         --post-data "token=${{ secrets.COVERITY_SCAN_TOKEN }}&project=${PROJECT_NAME}" \
         -O ${COVERITY_TGZ_PATH}

    - name: Coverity, unpack
      run: |
        mkdir -p "${COVERITY_ROOT}"
        tar xzf "${COVERITY_TGZ_PATH}" --strip 1 -C "${COVERITY_ROOT}"

    - name: Coverity, configure compiler/gcc
      run: |
        export PATH="${COVERITY_ROOT}/bin:$PATH"
        cov-configure --gcc

    - name: Coverity, build xNVMe
      run: |
        export PATH="${COVERITY_ROOT}/bin:$PATH"
        make clean config
        cov-build --dir cov-int make

    - name: Coverity, submit results for analysis
      run: |
        tar czvf "${PROJECT_NAME}_cov.tgz" cov-int
        curl --form token=${{ secrets.COVERITY_SCAN_TOKEN }} \
        --form email=${{ secrets.COVERITY_SCAN_EMAIL }} \
        --form file=@${PROJECT_NAME}_cov.tgz \
        --form version="v${PROJECT_VERSION}" \
        --form description="xNVMe libraries and tools for NVMe" \
        "https://scan.coverity.com/builds?project=${PROJECT_NAME}"

  packaging-debian:
    needs: source-archive
    runs-on: ubuntu-latest
    container: ghcr.io/xnvme/xnvme-deps-debian-packaging:main
    if: github.event_name == 'pull_request'

    steps:
    - name: Info
      run: |
        echo "Current branch is ${{ github.base_ref }}"
        echo "Current tag is ${{ github.ref }}"

    - name: Retrieve and unpack the xNVMe source archive
      uses: xnvme/actions/.github/actions/setup-source@main
      id: source
      with:
        name: xnvme-src-archive

    - name: Retrieve the xNVMe Debian package repository by branch
      run: |
        git clone https://salsa.debian.org/safl/xnvme.git debpkg
        git -C debpkg checkout ${{ github.base_ref }}

    - name: Prep
      run: |
        cp ${{ steps.source.outputs.src_tgz }} debpkg/input/xnvme-0.7.5.tar.gz

    - name: Build
      run: |
        cd debpkg && make || true

    - name: Upload debian packages
      uses: actions/upload-artifact@v4.3.0
      with:
        name: packages-debian
        path: |
          debpkg/builddir/libxnvme*.deb
          debpkg/builddir/xnvme-cli*.deb
          debpkg/builddir/xnvme-full*.deb
          debpkg/builddir/*.dsc
          debpkg/builddir/*.buildinfo
          debpkg/builddir/*.changes

